package com.demarqui.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.demarqui.demo.model.Veiculo;
import com.demarqui.demo.repository.VeiculoRepository;

@Controller // This means that this class is a Controller
@RequestMapping("/veiculo")// Url Request
public class VeiculoController {
	
	@Autowired
	private VeiculoRepository veiculoRepository;
	// This means to get the bean called veiculoRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	
	
	@PostMapping("/add") //POST requests...
	public @ResponseBody String addNewVeiculo (@RequestParam String marca
			,@RequestParam String modelo, @RequestParam int placa) {
		
		// @ResponseBody means the returned String is the response, not a view name
	    // @RequestParam means it is a parameter from the GET or POST request
		
		Veiculo v = new Veiculo(); 
		v.setMarca(marca);
		v.setModelo(modelo);
		v.setPlaca(placa);
		//Fazendo SET do objeto Veiculo
		veiculoRepository.save(v); 
		return "Saved";
	}
	
	@GetMapping("/all")//GET requests...
	public @ResponseBody Iterable<Veiculo> GetAllCars(){
	    // This returns a JSON or XML with the users
		return veiculoRepository.findAll();
	}
			
}
